name: CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: "Build and Depoy for ${{ matrix.RUNTIME }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        RUNTIME: [win-x64]
    env:
      CONFIGURATION: Release
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 7.x

      - name: Publish
        run: dotnet publish "./Labyrinth.Console/Labyrinth.Console.csproj" --configuration "${{ env.CONFIGURATION }}" --runtime "${{ matrix.RUNTIME }}" --output "./artifacts/${{ matrix.RUNTIME }}"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: "Artifact: ${{ matrix.RUNTIME }}"
          path: "./artifacts/${{ matrix.RUNTIME }}"
      
